### ISSUE TITLE
Pokus o smazání vydry, která má dceru

### ISSUE THREAD

**Issue by TomasKazda** [pslib-cz/2020p3web-ottersdb-OndrejBednar#1]
The DELETE statement conflicted with the SAME TABLE REFERENCE constraint "FK_Otters_Otters_MotherId". The conflict occurred in database "OttersDatabase", table "dbo.Otters", column 'MotherId'.

**Comment by OndrejBednar** [comment]
Úprava metody DeleteOtterAsync nyní kontroluje zda má vydra nějaké děti a pokud má, tak jim nastaví null do MotherId.
```csharp
                if (Otter.Children != null)
                {
                    foreach (var item in Otter.Children)
                    {
                        _context.Otters.Find(item.TattooID).MotherId = null;
                    }
                }
```
