### ISSUE TITLE
Neoprávněné smazání vydry

### ISSUE THREAD

**Issue by TomasKazda** [pslib-cz/2020p3web-ottersdb-OndrejBednar#2]
Lze smazat vydru, kde nejsem "founder"
https://localhost:44380/Delete?id=2

**Comment by OndrejBednar** [comment]
Metoda DeleteOtterAsync opravena přidáním verifikace uživatele [zde](https://github.com/pslib-cz/2020p3web-ottersdb-OndrejBednar/blob/1f40307595d85dce6588dcc51a3c5bf62201015e/OttersDatabase/Service/OttersService.cs#L66)
